#!/bin/bash

# Utility function to create virtual environments

venv_dir=$OPENSHIFT_PYTHON_DIR/virtenv/venv

function relative-virtenv {
  pushd "$venv_dir" > /dev/null

  vdir=$(cd "${venv_dir}" && pwd)
  for zf in $(grep -l -r "#\!$vdir/venv/bin/" . ); do
    sed --follow-symlinks -i "s;#\!$vdir/venv/bin/;#\!/usr/bin/env ;" "$zf"
  done

  popd > /dev/null
}

function create-virtenv {
  if [ ! -d "$venv_dir" ]  ||  ! $(ls "$venv_dir" > /dev/null 2>&1); then
    pyvenv --system-site-packages --clear $venv_dir
  fi

  relative-virtenv
}

function activate-virtenv {
  source $venv_dir/bin/activate
}
